### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by UltLight** [karyeet/Multi-Roblox#1]
seems like it's not working, I tried running it and it closed the first instance, like it was doing nothing at all

**Comment by karyeet** [comment]
Hey, just tested the executable from releases & re-compiled versions following the readme and it was working fine on my side.

- What version of Windows are you using?
- Did you run the executable before opening the roblox game?
- Are you using the roblox version from the Windows 10 Store or downloaded from roblox.com?
  - This program  only supports the version downloaded from roblox.com

**Comment by UltLight** [comment]
- Windows 10
- yes, I ran it before opening the game
- using the one downloaded from roblox.com

idk if this will help or not but I can't use NeoInversion's MultipleRobloxInstances (https://github.com/NeoInversion/MultipleRobloxInstances) either, which was the reason I looked for a different tool to use multiple instances in the first place.

**Comment by UltLight** [comment]
nvm I just had to restart my laptop for whatever reason, guess it's just windows being windows 🗿
thanks for responding
